# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_text', models.CharField(max_length=140)),
                ('date_time', models.DateTimeField(verbose_name='保存日')),
            ],
        ),
    ]
