# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageboard',
            name='new_message',
            field=models.TextField(),
        ),
    ]
